package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCacheOrder<M extends BaseCacheOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMachineSerial(java.lang.String machineSerial) {
		set("machineSerial", machineSerial);
	}
	
	public java.lang.String getMachineSerial() {
		return getStr("machineSerial");
	}

	public void setOrderPath(java.lang.String orderPath) {
		set("orderPath", orderPath);
	}
	
	public java.lang.String getOrderPath() {
		return getStr("orderPath");
	}

	public void setOrderValue(java.lang.String orderValue) {
		set("orderValue", orderValue);
	}
	
	public java.lang.String getOrderValue() {
		return getStr("orderValue");
	}

}
