package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTablesensorwarnpar<M extends BaseTablesensorwarnpar<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setProjectID(java.lang.Integer ProjectID) {
		set("ProjectID", ProjectID);
	}
	
	public java.lang.Integer getProjectID() {
		return getInt("ProjectID");
	}

	public void setDeviceID(java.lang.Integer DeviceID) {
		set("DeviceID", DeviceID);
	}
	
	public java.lang.Integer getDeviceID() {
		return getInt("DeviceID");
	}

	public void setSensorType(java.lang.Integer SensorType) {
		set("SensorType", SensorType);
	}
	
	public java.lang.Integer getSensorType() {
		return getInt("SensorType");
	}

	public void setRedEnable(java.lang.Integer redEnable) {
		set("Red_Enable", redEnable);
	}
	
	public java.lang.Integer getRedEnable() {
		return getInt("Red_Enable");
	}

	public void setRedOffsetSingle(java.lang.String redOffsetSingle) {
		set("Red_Offset_Single", redOffsetSingle);
	}
	
	public java.lang.String getRedOffsetSingle() {
		return getStr("Red_Offset_Single");
	}

	public void setRedOffsetCumulative(java.lang.String redOffsetCumulative) {
		set("Red_Offset_Cumulative", redOffsetCumulative);
	}
	
	public java.lang.String getRedOffsetCumulative() {
		return getStr("Red_Offset_Cumulative");
	}

	public void setOrangeEnable(java.lang.Integer orangeEnable) {
		set("Orange_Enable", orangeEnable);
	}
	
	public java.lang.Integer getOrangeEnable() {
		return getInt("Orange_Enable");
	}

	public void setOrangeOffsetSingle(java.lang.String orangeOffsetSingle) {
		set("Orange_Offset_Single", orangeOffsetSingle);
	}
	
	public java.lang.String getOrangeOffsetSingle() {
		return getStr("Orange_Offset_Single");
	}

	public void setOrangeOffsetCumulative(java.lang.String orangeOffsetCumulative) {
		set("Orange_Offset_Cumulative", orangeOffsetCumulative);
	}
	
	public java.lang.String getOrangeOffsetCumulative() {
		return getStr("Orange_Offset_Cumulative");
	}

	public void setYellowEnable(java.lang.Integer yellowEnable) {
		set("Yellow_Enable", yellowEnable);
	}
	
	public java.lang.Integer getYellowEnable() {
		return getInt("Yellow_Enable");
	}

	public void setYellowOffsetSingle(java.lang.String yellowOffsetSingle) {
		set("Yellow_Offset_Single", yellowOffsetSingle);
	}
	
	public java.lang.String getYellowOffsetSingle() {
		return getStr("Yellow_Offset_Single");
	}

	public void setYellowOffsetCumulative(java.lang.String yellowOffsetCumulative) {
		set("Yellow_Offset_Cumulative", yellowOffsetCumulative);
	}
	
	public java.lang.String getYellowOffsetCumulative() {
		return getStr("Yellow_Offset_Cumulative");
	}

	public void setBlueEnable(java.lang.Integer blueEnable) {
		set("Blue_Enable", blueEnable);
	}
	
	public java.lang.Integer getBlueEnable() {
		return getInt("Blue_Enable");
	}

	public void setBlueOffsetSingle(java.lang.String blueOffsetSingle) {
		set("Blue_Offset_Single", blueOffsetSingle);
	}
	
	public java.lang.String getBlueOffsetSingle() {
		return getStr("Blue_Offset_Single");
	}

	public void setBlueOffsetCumulative(java.lang.String blueOffsetCumulative) {
		set("Blue_Offset_Cumulative", blueOffsetCumulative);
	}
	
	public java.lang.String getBlueOffsetCumulative() {
		return getStr("Blue_Offset_Cumulative");
	}

	public void setStateEnable(java.lang.Integer stateEnable) {
		set("State_Enable", stateEnable);
	}
	
	public java.lang.Integer getStateEnable() {
		return getInt("State_Enable");
	}

	public void setElectricityQuantity(java.lang.Integer electricityQuantity) {
		set("Electricity_Quantity", electricityQuantity);
	}
	
	public java.lang.Integer getElectricityQuantity() {
		return getInt("Electricity_Quantity");
	}

	public void setDisconnection(java.lang.Integer Disconnection) {
		set("Disconnection", Disconnection);
	}
	
	public java.lang.Integer getDisconnection() {
		return getInt("Disconnection");
	}

	public void setNoResult(java.lang.Integer NoResult) {
		set("NoResult", NoResult);
	}
	
	public java.lang.Integer getNoResult() {
		return getInt("NoResult");
	}

}
