package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceGnssdata<M extends BaseDeviceGnssdata<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}
	
	public java.lang.Double getLat() {
		return getDouble("lat");
	}

	public void setLon(java.lang.Double lon) {
		set("lon", lon);
	}
	
	public java.lang.Double getLon() {
		return getDouble("lon");
	}

	public void setHeight(java.lang.Double height) {
		set("height", height);
	}
	
	public java.lang.Double getHeight() {
		return getDouble("height");
	}

	public void setCreatetiontime(java.lang.String createtiontime) {
		set("createtiontime", createtiontime);
	}
	
	public java.lang.String getCreatetiontime() {
		return getStr("createtiontime");
	}

}
