package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUpdateData<M extends BaseUpdateData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMachineSerial(java.lang.String machineSerial) {
		set("machineSerial", machineSerial);
	}
	
	public java.lang.String getMachineSerial() {
		return getStr("machineSerial");
	}

	public void setUpdateState(java.lang.Integer updateState) {
		set("updateState", updateState);
	}
	
	public java.lang.Integer getUpdateState() {
		return getInt("updateState");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("updateTime");
	}

}
