package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVersionData<M extends BaseVersionData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setVersionCode(java.lang.Integer versionCode) {
		set("versionCode", versionCode);
	}
	
	public java.lang.Integer getVersionCode() {
		return getInt("versionCode");
	}

	public void setDownloadUrl(java.lang.String downloadUrl) {
		set("downloadUrl", downloadUrl);
	}
	
	public java.lang.String getDownloadUrl() {
		return getStr("downloadUrl");
	}

	public void setVersionType(java.lang.Integer versionType) {
		set("versionType", versionType);
	}
	
	public java.lang.Integer getVersionType() {
		return getInt("versionType");
	}

}
