package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVersionDataCopy1<M extends BaseVersionDataCopy1<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAppModel(java.lang.String appModel) {
		set("appModel", appModel);
	}
	
	public java.lang.String getAppModel() {
		return getStr("appModel");
	}

	public void setVersionCode(java.lang.String versionCode) {
		set("versionCode", versionCode);
	}
	
	public java.lang.String getVersionCode() {
		return getStr("versionCode");
	}

	public void setVersinContent(java.lang.String versinContent) {
		set("versinContent", versinContent);
	}
	
	public java.lang.String getVersinContent() {
		return getStr("versinContent");
	}

	public void setVerAddress(java.lang.String verAddress) {
		set("verAddress", verAddress);
	}
	
	public java.lang.String getVerAddress() {
		return getStr("verAddress");
	}

}
