package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public void setAccessToken(java.lang.String accessToken) {
		set("accessToken", accessToken);
	}
	
	public java.lang.String getAccessToken() {
		return getStr("accessToken");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

	public void setExpireAt(java.lang.Long expireAt) {
		set("expireAt", expireAt);
	}
	
	public java.lang.Long getExpireAt() {
		return getLong("expireAt");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

}
