package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTakeNote<M extends BaseTakeNote<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMachineSerial(java.lang.String machineSerial) {
		set("machineSerial", machineSerial);
	}
	
	public java.lang.String getMachineSerial() {
		return getStr("machineSerial");
	}

	public void setFunProperties(java.lang.String funProperties) {
		set("funProperties", funProperties);
	}
	
	public java.lang.String getFunProperties() {
		return getStr("funProperties");
	}

	public void setNoteOrder(java.lang.String noteOrder) {
		set("noteOrder", noteOrder);
	}
	
	public java.lang.String getNoteOrder() {
		return getStr("noteOrder");
	}

	public void setResSate(java.lang.Integer ResSate) {
		set("ResSate", ResSate);
	}
	
	public java.lang.Integer getResSate() {
		return getInt("ResSate");
	}

	public void setWorkTime(java.lang.String workTime) {
		set("workTime", workTime);
	}
	
	public java.lang.String getWorkTime() {
		return getStr("workTime");
	}

	public void setOrderDetail(java.lang.String orderDetail) {
		set("orderDetail", orderDetail);
	}
	
	public java.lang.String getOrderDetail() {
		return getStr("orderDetail");
	}

	public void setSetFormwork(java.lang.Integer setFormwork) {
		set("setFormwork", setFormwork);
	}
	
	public java.lang.Integer getSetFormwork() {
		return getInt("setFormwork");
	}

}
