package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectsData<M extends BaseProjectsData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public void setProGroupId(java.lang.Integer proGroupId) {
		set("proGroupId", proGroupId);
	}
	
	public java.lang.Integer getProGroupId() {
		return getInt("proGroupId");
	}

	public void setProGroupName(java.lang.String proGroupName) {
		set("proGroupName", proGroupName);
	}
	
	public java.lang.String getProGroupName() {
		return getStr("proGroupName");
	}

	public void setAgentNumber(java.lang.String agentNumber) {
		set("agentNumber", agentNumber);
	}
	
	public java.lang.String getAgentNumber() {
		return getStr("agentNumber");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
