package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSensorData<M extends BaseSensorData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSensorType(java.lang.String sensorType) {
		set("sensorType", sensorType);
	}
	
	public java.lang.String getSensorType() {
		return getStr("sensorType");
	}

	public void setSensorVender(java.lang.String sensorVender) {
		set("sensorVender", sensorVender);
	}
	
	public java.lang.String getSensorVender() {
		return getStr("sensorVender");
	}

	public void setVenderName(java.lang.String venderName) {
		set("venderName", venderName);
	}
	
	public java.lang.String getVenderName() {
		return getStr("venderName");
	}

	public void setSensorCmd(java.lang.String sensorCmd) {
		set("sensorCmd", sensorCmd);
	}
	
	public java.lang.String getSensorCmd() {
		return getStr("sensorCmd");
	}

}
