package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setProID(java.lang.String proID) {
		set("proID", proID);
	}
	
	public java.lang.String getProID() {
		return getStr("proID");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}
	
	public java.lang.Double getLat() {
		return getDouble("lat");
	}

	public void setLon(java.lang.Double lon) {
		set("lon", lon);
	}
	
	public java.lang.Double getLon() {
		return getDouble("lon");
	}

	public void setProfile(java.lang.String profile) {
		set("profile", profile);
	}
	
	public java.lang.String getProfile() {
		return getStr("profile");
	}

	public void setIncharge(java.lang.String incharge) {
		set("incharge", incharge);
	}
	
	public java.lang.String getIncharge() {
		return getStr("incharge");
	}

	public void setEquipment(java.lang.String equipment) {
		set("equipment", equipment);
	}
	
	public java.lang.String getEquipment() {
		return getStr("equipment");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public void setCreationtime(java.lang.String creationtime) {
		set("creationtime", creationtime);
	}
	
	public java.lang.String getCreationtime() {
		return getStr("creationtime");
	}

}
