package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTemplateData<M extends BaseTemplateData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTemplateName(java.lang.String templateName) {
		set("templateName", templateName);
	}
	
	public java.lang.String getTemplateName() {
		return getStr("templateName");
	}

	public void setUAccountNumber(java.lang.String uAccountNumber) {
		set("uAccountNumber", uAccountNumber);
	}
	
	public java.lang.String getUAccountNumber() {
		return getStr("uAccountNumber");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setTemplateOrder(java.lang.String templateOrder) {
		set("templateOrder", templateOrder);
	}
	
	public java.lang.String getTemplateOrder() {
		return getStr("templateOrder");
	}

	public void setAgentNumber(java.lang.String agentNumber) {
		set("agentNumber", agentNumber);
	}
	
	public java.lang.String getAgentNumber() {
		return getStr("agentNumber");
	}

}
