package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTabledevicewarnpar<M extends BaseTabledevicewarnpar<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setProjectID(java.lang.Integer ProjectID) {
		set("ProjectID", ProjectID);
	}
	
	public java.lang.Integer getProjectID() {
		return getInt("ProjectID");
	}

	public void setDeviceID(java.lang.Integer DeviceID) {
		set("DeviceID", DeviceID);
	}
	
	public java.lang.Integer getDeviceID() {
		return getInt("DeviceID");
	}

	public void setRedEnable(java.lang.Integer redEnable) {
		set("Red_Enable", redEnable);
	}
	
	public java.lang.Integer getRedEnable() {
		return getInt("Red_Enable");
	}

	public void setRedOffsetSingleHorizontal(java.lang.Integer redOffsetSingleHorizontal) {
		set("Red_Offset_Single_Horizontal", redOffsetSingleHorizontal);
	}
	
	public java.lang.Integer getRedOffsetSingleHorizontal() {
		return getInt("Red_Offset_Single_Horizontal");
	}

	public void setRedOffsetSingleVertical(java.lang.Integer redOffsetSingleVertical) {
		set("Red_Offset_Single_Vertical", redOffsetSingleVertical);
	}
	
	public java.lang.Integer getRedOffsetSingleVertical() {
		return getInt("Red_Offset_Single_Vertical");
	}

	public void setRedOffsetCumulativeHorizontal(java.lang.Integer redOffsetCumulativeHorizontal) {
		set("Red_Offset_Cumulative_Horizontal", redOffsetCumulativeHorizontal);
	}
	
	public java.lang.Integer getRedOffsetCumulativeHorizontal() {
		return getInt("Red_Offset_Cumulative_Horizontal");
	}

	public void setRedOffsetCumulativeVertical(java.lang.Integer redOffsetCumulativeVertical) {
		set("Red_Offset_Cumulative_Vertical", redOffsetCumulativeVertical);
	}
	
	public java.lang.Integer getRedOffsetCumulativeVertical() {
		return getInt("Red_Offset_Cumulative_Vertical");
	}

	public void setOrangeEnable(java.lang.Integer orangeEnable) {
		set("Orange_Enable", orangeEnable);
	}
	
	public java.lang.Integer getOrangeEnable() {
		return getInt("Orange_Enable");
	}

	public void setOrangeOffsetSingleHorizontal(java.lang.Integer orangeOffsetSingleHorizontal) {
		set("Orange_Offset_Single_Horizontal", orangeOffsetSingleHorizontal);
	}
	
	public java.lang.Integer getOrangeOffsetSingleHorizontal() {
		return getInt("Orange_Offset_Single_Horizontal");
	}

	public void setOrangeOffsetSingleVertical(java.lang.Integer orangeOffsetSingleVertical) {
		set("Orange_Offset_Single_Vertical", orangeOffsetSingleVertical);
	}
	
	public java.lang.Integer getOrangeOffsetSingleVertical() {
		return getInt("Orange_Offset_Single_Vertical");
	}

	public void setOrangeOffsetCumulativeHorizontal(java.lang.Integer orangeOffsetCumulativeHorizontal) {
		set("Orange_Offset_Cumulative_Horizontal", orangeOffsetCumulativeHorizontal);
	}
	
	public java.lang.Integer getOrangeOffsetCumulativeHorizontal() {
		return getInt("Orange_Offset_Cumulative_Horizontal");
	}

	public void setOrangeOffsetCumulativeVertical(java.lang.Integer orangeOffsetCumulativeVertical) {
		set("Orange_Offset_Cumulative_Vertical", orangeOffsetCumulativeVertical);
	}
	
	public java.lang.Integer getOrangeOffsetCumulativeVertical() {
		return getInt("Orange_Offset_Cumulative_Vertical");
	}

	public void setYellowEnable(java.lang.Integer yellowEnable) {
		set("Yellow_Enable", yellowEnable);
	}
	
	public java.lang.Integer getYellowEnable() {
		return getInt("Yellow_Enable");
	}

	public void setYellowOffsetSingleHorizontal(java.lang.Integer yellowOffsetSingleHorizontal) {
		set("Yellow_Offset_Single_Horizontal", yellowOffsetSingleHorizontal);
	}
	
	public java.lang.Integer getYellowOffsetSingleHorizontal() {
		return getInt("Yellow_Offset_Single_Horizontal");
	}

	public void setYellowOffsetSingleVertical(java.lang.Integer yellowOffsetSingleVertical) {
		set("Yellow_Offset_Single_Vertical", yellowOffsetSingleVertical);
	}
	
	public java.lang.Integer getYellowOffsetSingleVertical() {
		return getInt("Yellow_Offset_Single_Vertical");
	}

	public void setYellowOffsetCumulativeHorizontal(java.lang.Integer yellowOffsetCumulativeHorizontal) {
		set("Yellow_Offset_Cumulative_Horizontal", yellowOffsetCumulativeHorizontal);
	}
	
	public java.lang.Integer getYellowOffsetCumulativeHorizontal() {
		return getInt("Yellow_Offset_Cumulative_Horizontal");
	}

	public void setYellowOffsetCumulativeVertical(java.lang.Integer yellowOffsetCumulativeVertical) {
		set("Yellow_Offset_Cumulative_Vertical", yellowOffsetCumulativeVertical);
	}
	
	public java.lang.Integer getYellowOffsetCumulativeVertical() {
		return getInt("Yellow_Offset_Cumulative_Vertical");
	}

	public void setBlueEnable(java.lang.Integer blueEnable) {
		set("Blue_Enable", blueEnable);
	}
	
	public java.lang.Integer getBlueEnable() {
		return getInt("Blue_Enable");
	}

	public void setBlueOffsetSingleHorizontal(java.lang.Integer blueOffsetSingleHorizontal) {
		set("Blue_Offset_Single_Horizontal", blueOffsetSingleHorizontal);
	}
	
	public java.lang.Integer getBlueOffsetSingleHorizontal() {
		return getInt("Blue_Offset_Single_Horizontal");
	}

	public void setBlueOffsetSingleVertical(java.lang.Integer blueOffsetSingleVertical) {
		set("Blue_Offset_Single_Vertical", blueOffsetSingleVertical);
	}
	
	public java.lang.Integer getBlueOffsetSingleVertical() {
		return getInt("Blue_Offset_Single_Vertical");
	}

	public void setBlueOffsetCumulativeHorizontal(java.lang.Integer blueOffsetCumulativeHorizontal) {
		set("Blue_Offset_Cumulative_Horizontal", blueOffsetCumulativeHorizontal);
	}
	
	public java.lang.Integer getBlueOffsetCumulativeHorizontal() {
		return getInt("Blue_Offset_Cumulative_Horizontal");
	}

	public void setBlueOffsetCumulativeVertical(java.lang.Integer blueOffsetCumulativeVertical) {
		set("Blue_Offset_Cumulative_Vertical", blueOffsetCumulativeVertical);
	}
	
	public java.lang.Integer getBlueOffsetCumulativeVertical() {
		return getInt("Blue_Offset_Cumulative_Vertical");
	}

	public void setStateEnable(java.lang.Integer stateEnable) {
		set("State_Enable", stateEnable);
	}
	
	public java.lang.Integer getStateEnable() {
		return getInt("State_Enable");
	}

	public void setElectricityQuantity(java.lang.Integer electricityQuantity) {
		set("Electricity_Quantity", electricityQuantity);
	}
	
	public java.lang.Integer getElectricityQuantity() {
		return getInt("Electricity_Quantity");
	}

	public void setDisconnection(java.lang.Integer Disconnection) {
		set("Disconnection", Disconnection);
	}
	
	public java.lang.Integer getDisconnection() {
		return getInt("Disconnection");
	}

	public void setNoResult(java.lang.Integer NoResult) {
		set("NoResult", NoResult);
	}
	
	public java.lang.Integer getNoResult() {
		return getInt("NoResult");
	}

}
