package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTableuserinfo<M extends BaseTableuserinfo<M>> extends Model<M> implements IBean {

	public void setUserID(java.lang.String UserID) {
		set("UserID", UserID);
	}
	
	public java.lang.String getUserID() {
		return getStr("UserID");
	}

	public void setUserGrade(java.lang.Integer UserGrade) {
		set("UserGrade", UserGrade);
	}
	
	public java.lang.Integer getUserGrade() {
		return getInt("UserGrade");
	}

	public void setPassword(java.lang.String Password) {
		set("Password", Password);
	}
	
	public java.lang.String getPassword() {
		return getStr("Password");
	}

	public void setUserName(java.lang.String UserName) {
		set("UserName", UserName);
	}
	
	public java.lang.String getUserName() {
		return getStr("UserName");
	}

	public void setPID(java.lang.String PID) {
		set("PID", PID);
	}
	
	public java.lang.String getPID() {
		return getStr("PID");
	}

	public void setCompany(java.lang.String Company) {
		set("Company", Company);
	}
	
	public java.lang.String getCompany() {
		return getStr("Company");
	}

	public void setEducation(java.lang.String Education) {
		set("Education", Education);
	}
	
	public java.lang.String getEducation() {
		return getStr("Education");
	}

	public void setDegree(java.lang.String Degree) {
		set("Degree", Degree);
	}
	
	public java.lang.String getDegree() {
		return getStr("Degree");
	}

	public void setTelephone(java.lang.String Telephone) {
		set("Telephone", Telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("Telephone");
	}

	public void setEmail(java.lang.String Email) {
		set("Email", Email);
	}
	
	public java.lang.String getEmail() {
		return getStr("Email");
	}

	public void setQQ(java.lang.String QQ) {
		set("QQ", QQ);
	}
	
	public java.lang.String getQQ() {
		return getStr("QQ");
	}

	public void setImage(java.lang.String Image) {
		set("Image", Image);
	}
	
	public java.lang.String getImage() {
		return getStr("Image");
	}

	public void setCertificate(java.lang.String Certificate) {
		set("Certificate", Certificate);
	}
	
	public java.lang.String getCertificate() {
		return getStr("Certificate");
	}

	public void setJob(java.lang.String Job) {
		set("Job", Job);
	}
	
	public java.lang.String getJob() {
		return getStr("Job");
	}

	public void setQualifications(java.lang.String Qualifications) {
		set("Qualifications", Qualifications);
	}
	
	public java.lang.String getQualifications() {
		return getStr("Qualifications");
	}

	public void setLoginDateTime(java.lang.String LoginDateTime) {
		set("LoginDateTime", LoginDateTime);
	}
	
	public java.lang.String getLoginDateTime() {
		return getStr("LoginDateTime");
	}

	public void setProjectAuthority(java.lang.String ProjectAuthority) {
		set("ProjectAuthority", ProjectAuthority);
	}
	
	public java.lang.String getProjectAuthority() {
		return getStr("ProjectAuthority");
	}

}
