package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceSensordict<M extends BaseDeviceSensordict<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setKeyname1(java.lang.String keyname1) {
		set("keyname1", keyname1);
	}
	
	public java.lang.String getKeyname1() {
		return getStr("keyname1");
	}

	public void setKeyname2(java.lang.String keyname2) {
		set("keyname2", keyname2);
	}
	
	public java.lang.String getKeyname2() {
		return getStr("keyname2");
	}

	public void setCreatetiontime(java.lang.String createtiontime) {
		set("createtiontime", createtiontime);
	}
	
	public java.lang.String getCreatetiontime() {
		return getStr("createtiontime");
	}

}
