package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceWarnlog<M extends BaseDeviceWarnlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setCreatetiontime(java.lang.String createtiontime) {
		set("createtiontime", createtiontime);
	}
	
	public java.lang.String getCreatetiontime() {
		return getStr("createtiontime");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setSolvetype(java.lang.Integer solvetype) {
		set("solvetype", solvetype);
	}
	
	public java.lang.Integer getSolvetype() {
		return getInt("solvetype");
	}

	public void setSolvenote(java.lang.String solvenote) {
		set("solvenote", solvenote);
	}
	
	public java.lang.String getSolvenote() {
		return getStr("solvenote");
	}

	public void setSolvetime(java.lang.String solvetime) {
		set("solvetime", solvetime);
	}
	
	public java.lang.String getSolvetime() {
		return getStr("solvetime");
	}

	public void setSolveperson(java.lang.String solveperson) {
		set("solveperson", solveperson);
	}
	
	public java.lang.String getSolveperson() {
		return getStr("solveperson");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setProjectid(java.lang.String projectid) {
		set("projectid", projectid);
	}
	
	public java.lang.String getProjectid() {
		return getStr("projectid");
	}

}
