package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAgentTable<M extends BaseAgentTable<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAgentNumber(java.lang.String agentNumber) {
		set("agentNumber", agentNumber);
	}
	
	public java.lang.String getAgentNumber() {
		return getStr("agentNumber");
	}

	public void setAgentName(java.lang.String agentName) {
		set("agentName", agentName);
	}
	
	public java.lang.String getAgentName() {
		return getStr("agentName");
	}

	public void setAppAuthority(java.lang.String appAuthority) {
		set("appAuthority", appAuthority);
	}
	
	public java.lang.String getAppAuthority() {
		return getStr("appAuthority");
	}

	public void setWebAuthority(java.lang.String webAuthority) {
		set("webAuthority", webAuthority);
	}
	
	public java.lang.String getWebAuthority() {
		return getStr("webAuthority");
	}

}
