package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceGnssoffset<M extends BaseDeviceGnssoffset<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setDx(java.lang.Double dx) {
		set("dx", dx);
	}
	
	public java.lang.Double getDx() {
		return getDouble("dx");
	}

	public void setDy(java.lang.Double dy) {
		set("dy", dy);
	}
	
	public java.lang.Double getDy() {
		return getDouble("dy");
	}

	public void setDz(java.lang.Double dz) {
		set("dz", dz);
	}
	
	public java.lang.Double getDz() {
		return getDouble("dz");
	}

	public void setCreatetiontime(java.lang.String createtiontime) {
		set("createtiontime", createtiontime);
	}
	
	public java.lang.String getCreatetiontime() {
		return getStr("createtiontime");
	}

}
