package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceGnsslog<M extends BaseDeviceGnsslog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setBattery(java.lang.String battery) {
		set("battery", battery);
	}
	
	public java.lang.String getBattery() {
		return getStr("battery");
	}

	public void setCreatetiontime(java.lang.String createtiontime) {
		set("createtiontime", createtiontime);
	}
	
	public java.lang.String getCreatetiontime() {
		return getStr("createtiontime");
	}

}
