package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBorrowData<M extends BaseBorrowData<M>> extends Model<M> implements IBean {

	public void setId(int id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setLender(java.lang.String lender) {
		set("lender", lender);
	}
	
	public java.lang.String getLender() {
		return getStr("lender");
	}

	public void setMachineSerial(java.lang.String machineSerial) {
		set("machineSerial", machineSerial);
	}
	
	public java.lang.String getMachineSerial() {
		return getStr("machineSerial");
	}

	public void setAgentNumber(java.lang.String agentNumber) {
		set("agentNumber", agentNumber);
	}
	
	public java.lang.String getAgentNumber() {
		return getStr("agentNumber");
	}

	public void setUAccountNum(java.lang.String uAccountNum) {
		set("uAccountNum", uAccountNum);
	}
	
	public java.lang.String getUAccountNum() {
		return getStr("uAccountNum");
	}

	public void setBeginTime(java.util.Date beginTime) {
		set("beginTime", beginTime);
	}
	
	public java.util.Date getBeginTime() {
		return get("beginTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("endTime");
	}


	public void setReturnStatus(java.lang.Integer returnStatus) {
		set("returnStatus", returnStatus);
	}
	
	public java.lang.Integer getReturnStatus() {
		return getInt("returnStatus");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phoneNumber", phoneNumber);
	}
	
	public java.lang.String getPhoneNumber() {
		return getStr("phoneNumber");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

}
