package com.webmonitor.core.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDevice<M extends BaseDevice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setProjectid(java.lang.String projectid) {
		set("projectid", projectid);
	}
	
	public java.lang.String getProjectid() {
		return getStr("projectid");
	}

	public void setStationname(java.lang.String stationname) {
		set("stationname", stationname);
	}
	
	public java.lang.String getStationname() {
		return getStr("stationname");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public void setTypeid(java.lang.String typeid) {
		set("typeid", typeid);
	}
	
	public java.lang.String getTypeid() {
		return getStr("typeid");
	}

	public void setOnline(java.lang.Integer online) {
		set("online", online);
	}
	
	public java.lang.Integer getOnline() {
		return getInt("online");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}
	
	public java.lang.Double getLat() {
		return getDouble("lat");
	}

	public void setLon(java.lang.Double lon) {
		set("lon", lon);
	}
	
	public java.lang.Double getLon() {
		return getDouble("lon");
	}

	public void setHeight(java.lang.Double height) {
		set("height", height);
	}
	
	public java.lang.Double getHeight() {
		return getDouble("height");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

}
