package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseAccountRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountRole extends BaseAccountRole<AccountRole> {
	public static final AccountRole dao = new AccountRole().dao();
}
