package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	public static final Account dao = new Account().dao();

	public static final int STATUS_LOCK_ID = -1;	// 锁定账号，无法做任何事情
	public static final int STATUS_OK = 1;			// 正常、已激活

	public static final int CLASS_SURPERADMIN = 10;	// 超级管理员
	public static final int CLASS_ADMIN = 1;			// 管理员
	public static final int CLASS_GENERAL= 0;			// 普通用户

	public boolean isStatusOk() {
		return getStatus() == STATUS_OK;
	}

	public boolean isStatusLockId() {
		return getStatus() == STATUS_LOCK_ID;
	}

	public Account removeSensitiveInfo() {
		remove("password", "salt");
		return this;
	}
}
