package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseAgentTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentTable extends BaseAgentTable<AgentTable> {
	public static final AgentTable dao = new AgentTable().dao();
}
