package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseBorrowData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BorrowData extends BaseBorrowData<BorrowData> {
	public static final BorrowData dao = new BorrowData().dao();
}
