package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseCacheOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CacheOrder extends BaseCacheOrder<CacheOrder> {
	public static final CacheOrder dao = new CacheOrder().dao();
}
