package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict().dao();
}
