package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseGroupsData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupsData extends BaseGroupsData<GroupsData> {
	public static final GroupsData dao = new GroupsData().dao();
}
