package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseMachineData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MachineData extends BaseMachineData<MachineData> {
	public static final MachineData dao = new MachineData().dao();
}
