package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseMachineDataCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MachineDataCopy1 extends BaseMachineDataCopy1<MachineDataCopy1> {
	public static final MachineDataCopy1 dao = new MachineDataCopy1().dao();
}
