package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseProjectsData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectsData extends BaseProjectsData<ProjectsData> {
	public static final ProjectsData dao = new ProjectsData().dao();
}
