package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseSensorData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensorData extends BaseSensorData<SensorData> {
	public static final SensorData dao = new SensorData().dao();
}
