package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseStaffData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StaffData extends BaseStaffData<StaffData> {
	public static final StaffData dao = new StaffData().dao();
}
