package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseTakeNote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TakeNote extends BaseTakeNote<TakeNote> {
	public static final TakeNote dao = new TakeNote().dao();
}
