package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseTemplateData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TemplateData extends BaseTemplateData<TemplateData> {
	public static final TemplateData dao = new TemplateData().dao();
}
