package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseUpdateData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UpdateData extends BaseUpdateData<UpdateData> {
	public static final UpdateData dao = new UpdateData().dao();
}
