package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseVersionDataCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VersionDataCopy1 extends BaseVersionDataCopy1<VersionDataCopy1> {
	public static final VersionDataCopy1 dao = new VersionDataCopy1().dao();
}
