package com.webmonitor.core.model;

import com.webmonitor.core.model.base.BaseVersionData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VersionData extends BaseVersionData<VersionData> {
	public static final VersionData dao = new VersionData().dao();
}
